### ISSUE TITLE
samsupporttab

### ISSUE THREAD

**Issue by rajanikanthnmsu** [njdbickhart/RAPTR-SV#2]
Hi,
I think i sucessfully ran the preprocess mode. However, it also generates another file called Samsupport.tab which you did not mention in the readme. Could you please clarify.

Thanks
Raj

**Comment by njdbickhart** [comment]
Hello Raj,

This is a good point! Samsupport.tab is generated only from the "-d" flag as a means of debugging the program. It is a simple "dump" of all discordant reads from the input BAM file, and can be safely removed after running the program. 

I will edit the readme to explain this better.

Thank you,
Derek
